### ISSUE TITLE
some  questions

### ISSUE THREAD

**Issue by cornerll** [rafael-fuente/N-body-numerical-simulation#2]
Dear rafael, I have some questions about the program. I want to know how to set the number of the particles and let the simulation auto-run without pulling the time line below the figure. I just mean how to make it like your examples of the video on youtube. Thanks a lot.

**Comment by rafael-fuente** [comment]
For setting a new particle just create the particle with `Particle()` constructor and add to the current list of particles `par` with append() method.

Particle() constructor takes two arguments, the first is the initial position of the particle and the second is the initial velocity.
```
#create the particles
par.append(Particle(Vec2(2,5),Vec2(0.5,0.5)))
par.append(Particle(Vec2(5,2),Vec2(0.5,0.2)))
par.append(Particle(Vec2(3,3),Vec2(0.1,0.5)))
par.append(Particle(Vec2(0.6,2.5),Vec2(0.5,0.5)))
```

For my youtube video I render the simulation frame by frame and the I merged all frames in to a video using [ffmpeg](https://ffmpeg.org/)

An alternative for doing directly for matplotlib is using [matplotlib.animation.ArtistAnimation](https://matplotlib.org/gallery/animation/dynamic_image2.html), but unless you want make a video to post it somewhere for testing it's better an slider because it allows seeing easily any instant of the simulation.

Sorry for the delay in replying, I missed the notification.
